# Guion del vídeo de YouTube «Por qué buscar trabajo se ha roto (y cómo arreglarlo)».
# (id, capítulo, texto en pantalla/subtítulo, texto para la voz (fonético cuando hace falta), pausa después en s)
#
# Nota: el guion evita cifras concretas que no podamos respaldar con una fuente. Si añades datos,
# cita la fuente en la descripción de YouTube.

CHAPTERS = {
    "intro": "Intro",
    "antes": "1. Cuando buscar trabajo era llamar a una puerta",
    "embudo": "2. El embudo digital",
    "ia": "3. IA contra IA",
    "funciona": "4. Lo que sí funciona",
    "knok": "5. Cómo lo resolvemos",
    "cierre": "Cierre",
}

LINES = [
    # ------------------------------------------------------------ intro
    ("i1", "intro", "Mandas cincuenta currículums. Pasan dos semanas. Y lo único que recibes es un correo automático que empieza por «Gracias por tu interés».",
     "Mandas cincuenta currículums. Pasan dos semanas. Y lo único que recibes, es un correo automático que empieza por: gracias por tu interés.", 0.6),
    ("i2", "intro", "Si te ha pasado, no eres tú. La forma de buscar trabajo ha cambiado más en los últimos años que en décadas.",
     "Si te ha pasado, no eres tú. La forma de buscar trabajo ha cambiado más en los últimos años, que en décadas.", 0.4),
    ("i3", "intro", "Hoy vamos a ver qué se ha roto, por qué la inteligencia artificial lo ha complicado aún más, y qué puedes hacer para que te llamen.",
     "Hoy vamos a ver qué se ha roto, por qué la inteligencia artificial lo ha complicado aún más, y qué puedes hacer para que te llamen.", 3.0),
    # ------------------------------------------------------------ 1. antes
    ("a1", "antes", "Hace no tanto, buscar trabajo era sobre todo una cuestión de puertas.",
     "Hace no tanto, buscar trabajo era, sobre todo, una cuestión de puertas.", 0.4),
    ("a2", "antes", "Imprimías tu currículum, ibas a la empresa y se lo dabas a una persona. Esa persona te veía, te escuchaba y, con suerte, se acordaba de ti.",
     "Imprimías tu currículum, ibas a la empresa, y se lo dabas a una persona. Esa persona te veía, te escuchaba, y, con suerte, se acordaba de ti.", 0.4),
    ("a3", "antes", "Había menos ofertas y menos candidatos por oferta. Lento, sí. Pero humano.",
     "Había menos ofertas, y menos candidatos por oferta. Lento, sí. Pero humano.", 3.0),
    # ------------------------------------------------------------ 2. el embudo
    ("b1", "embudo", "Luego llegaron los portales de empleo. Y con ellos, el botón de «solicitud rápida».",
     "Luego llegaron los portales de empleo. Y con ellos, el botón de, solicitud rápida.", 0.4),
    ("b2", "embudo", "De repente, aplicar costaba un clic. Y cuando algo cuesta un clic, lo hace todo el mundo.",
     "De repente, aplicar costaba un clic. Y cuando algo cuesta un clic, lo hace todo el mundo.", 0.4),
    ("b3", "embudo", "Una sola oferta puede recibir cientos de candidaturas en pocos días. Nadie puede leerlas todas con calma.",
     "Una sola oferta puede recibir cientos de candidaturas en pocos días. Nadie puede leerlas todas con calma.", 0.4),
    ("b4", "embudo", "Así que muchas empresas usan filtros automáticos: programas que leen tu currículum antes que cualquier persona, buscan palabras clave y descartan en segundos.",
     "Así que muchas empresas usan filtros automáticos. Programas que leen tu currículum antes que cualquier persona, buscan palabras clave, y descartan en segundos.", 0.4),
    ("b4b", "embudo", "Por eso a veces te descartan sin que nadie haya leído tu currículum. No porque no valgas, sino porque no aparecían las palabras que buscaba el filtro.",
     "Por eso, a veces te descartan sin que nadie haya leído tu currículum. No porque no valgas, sino porque no aparecían las palabras que buscaba el filtro.", 0.4),
    ("b5", "embudo", "El resultado es un embudo gigante: muchísimas candidaturas arriba… y muy pocas conversaciones abajo.",
     "El resultado es un embudo gigante. Muchísimas candidaturas arriba… y muy pocas conversaciones abajo.", 3.0),
    # ------------------------------------------------------------ 3. IA contra IA
    ("c1", "ia", "Y entonces llegó la inteligencia artificial.",
     "Y entonces, llegó la inteligencia artificial.", 0.5),
    ("c2", "ia", "Los candidatos empezaron a usarla para escribir sus cartas. Las empresas, para leerlas.",
     "Los candidatos empezaron a usarla para escribir sus cartas. Las empresas, para leerlas.", 0.4),
    ("c3", "ia", "Si todos usamos la misma herramienta de la misma forma, todas las cartas acaban sonando igual: «Me apasiona aportar valor a un equipo dinámico».",
     "Y si todos usamos la misma herramienta, de la misma forma, todas las cartas acaban sonando igual. Me apasiona aportar valor, a un equipo dinámico.", 0.4),
    ("c4", "ia", "Una IA escribe, otra IA filtra. Y en medio estás tú, intentando que alguien vea a la persona que hay detrás.",
     "Una ía escribe. Otra ía filtra. Y en medio estás tú, intentando que alguien vea a la persona que hay detrás.", 0.4),
    ("c5", "ia", "La respuesta no es mandar más. Es mandar mejor.",
     "La respuesta no es mandar más. Es mandar mejor.", 0.5),
    ("c6", "ia", "Y aquí hay una buena noticia: cuando todo suena igual, lo auténtico destaca más que nunca.",
     "Y aquí hay una buena noticia. Cuando todo suena igual, lo auténtico destaca más que nunca.", 3.0),
    # ------------------------------------------------------------ 4. lo que funciona
    ("d1", "funciona", "Si hablas con gente que se dedica a seleccionar personal, casi todos repiten las mismas tres ideas.",
     "Si hablas con gente que se dedica a seleccionar personal, casi todos repiten las mismas tres ideas.", 0.4),
    ("d2", "funciona", "Uno: menos y mejor. Unas pocas candidaturas bien pensadas suelen funcionar mejor que cien iguales.",
     "Uno. Menos, y mejor. Unas pocas candidaturas bien pensadas suelen funcionar mejor que cien iguales.", 0.4),
    ("d3", "funciona", "Dos: personaliza de verdad. No basta con cambiar el nombre de la empresa. Demuestra que sabes qué hacen y por qué encajas tú.",
     "Dos. Personaliza de verdad. No basta con cambiar el nombre de la empresa. Demuestra que sabes qué hacen, y por qué encajas tú.", 0.4),
    ("d4", "funciona", "Y tres: apunta bien. Busca ofertas que encajen con tu perfil, tu ciudad y lo que quieres cobrar. Aplicar donde no encajas solo alimenta al filtro.",
     "Y tres. Apunta bien. Busca ofertas que encajen con tu perfil, tu ciudad, y lo que quieres cobrar. Aplicar donde no encajas, solo alimenta al filtro.", 0.4),
    ("d4b", "funciona", "Un truco: lee la oferta tres veces y subraya lo que más se repite. Esas son las palabras que deberían encontrar el filtro… y la persona.",
     "Un truco. Lee la oferta tres veces, y subraya lo que más se repite. Esas son las palabras que deberían encontrar el filtro… y la persona.", 0.4),
    ("d4c", "funciona", "Y un extra: haz seguimiento. Un mensaje amable una semana después puede rescatar una candidatura olvidada.",
     "Y un extra. Haz seguimiento. Un mensaje amable una semana después, puede rescatar una candidatura olvidada.", 0.4),
    ("d5", "funciona", "El problema es que hacer todo esto bien lleva horas. Muchas horas.",
     "El problema, es que hacer todo esto bien, lleva horas. Muchas horas.", 3.0),
    # ------------------------------------------------------------ 5. knok
    ("e1", "knok", "Por eso creamos knok.",
     "Por eso, creamos nok.", 0.5),
    ("e2", "knok", "knok busca por todo internet las ofertas que encajan con lo que pides, y te dice por qué encajan.",
     "Nok busca por todo internet las ofertas que encajan con lo que pides, y te dice por qué encajan.", 0.4),
    ("e3", "knok", "Después escribe un correo distinto para cada empresa, con tu tono y tu historia, que puedes revisar y cambiar antes de enviarlo.",
     "Después, escribe un correo distinto para cada empresa, con tu tono y tu historia, que puedes revisar y cambiar antes de enviarlo.", 0.4),
    ("e4", "knok", "Y cuando lo tienes listo, lo envías todo con un solo clic.",
     "Y cuando lo tienes listo, lo envías todo, con un solo clic.", 0.4),
    ("e5", "knok", "Con su extensión para Chrome también puedes aplicar en LinkedIn y otros portales, sin rellenar el mismo formulario una y otra vez.",
     "Con su extensión para Crom, también puedes aplicar en Línkedin y otros portales, sin rellenar el mismo formulario una y otra vez.", 0.4),
    ("e6", "knok", "La idea no es sustituirte. Es quitarte lo repetitivo, para que te centres en lo importante: preparar la entrevista.",
     "La idea no es sustituirte. Es quitarte lo repetitivo, para que te centres en lo importante. Preparar la entrevista.", 1.0),
    ("e7", "knok", "Tú decides siempre qué se envía y a quién. knok solo te ahorra empezar de cero cada vez.",
     "Tú decides siempre qué se envía, y a quién. Nok solo te ahorra empezar de cero cada vez.", 3.0),
    ("r1", "cierre", "Resumen rápido: menos y mejor. Personaliza de verdad. Apunta bien. Haz seguimiento. Y deja lo repetitivo a una herramienta.",
     "Resumen rápido. Menos, y mejor. Personaliza de verdad. Apunta bien. Haz seguimiento. Y deja lo repetitivo, a una herramienta.", 0.6),
    # ------------------------------------------------------------ cierre
    ("f1", "cierre", "Buscar trabajo ha cambiado. Las reglas son nuevas, pero lo de siempre sigue funcionando: llamar a la puerta correcta, y hacerlo bien.",
     "Buscar trabajo ha cambiado. Las reglas son nuevas, pero lo de siempre sigue funcionando. Llamar a la puerta correcta, y hacerlo bien.", 0.5),
    ("f2", "cierre", "Si este vídeo te ha ayudado, compártelo con alguien que esté buscando. Y suscríbete para más.",
     "Si este vídeo te ha ayudado, compártelo con alguien que esté buscando. Y suscríbete, para más.", 0.4),
    ("f3", "cierre", "Nos vemos en el siguiente. Y que el futuro te abra la puerta.",
     "Nos vemos en el siguiente. Y que el futuro, te abra la puerta.", 0.0),
]
